server:
  port: 7060

spring:
  application:
    name: "gateway-service"

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:7070/eureka"
  instance:
    prefer-ip-address: true

security:
  basic:
    enabled: false


