server:
  port: 7071

spring:
  application:
    name: "user-service"
  redis:
    host: 192.168.18.103
    port: 6379
    password: ace@redis99
    database: 8
    timeout: 10s
    jedis:
      pool:
        max-active: 10
        max-idle: 5
        min-idle: 2
        max-wait: 2s

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:7070/eureka"

  instance:
    prefer-ip-address: true